### ISSUE TITLE
Address type inputs are not working

### ISSUE THREAD

**Issue by 0mkara** [quantanet/ethcode#42]
#### Error description

Address type inputs are not working for constructor inputs.

<img width="672" alt="Screenshot 2019-12-08 at 10 23 04 AM" src="https://user-images.githubusercontent.com/13261372/70384475-fb51e280-19a4-11ea-83d0-a4ff20b03994.png">

#### Error details
```JSON
{"code":2,"details":"Exception iterating responses: One or more arguments could not be encoded to the necessary ABI type.  Expected types are: address, uint256","metadata":{"internalRepr":{},"options":{}}}
```

**Comment by Soumyanil** [comment]
![image](https://user-images.githubusercontent.com/13421045/70410720-00cb2d80-1a76-11ea-93a7-04dd01bb7199.png)
Unable to reproduce the issue.
