### ISSUE TITLE
method call not working when method has no input params

### ISSUE THREAD

**Issue by 0mkara** [quantanet/ethcode#51]
```
/* Main function */
    function greet() public view returns (string memory) {
        return greeting;
    }
```
`greet` method will not work in ethcode.
![Screenshot from 2019-12-13 00-55-47](https://user-images.githubusercontent.com/13261372/70742401-76b7e900-1d43-11ea-99bb-0a29c6bd2f6e.png)

**Comment by Soumyanil** [comment]
Can recreate the issue
![image](https://user-images.githubusercontent.com/13421045/70771564-88c37700-1d97-11ea-9b75-c409e4614bce.png)
