### ISSUE TITLE
Account system UI/UX

### ISSUE THREAD

**Issue by 0mkara** [quantanet/ethcode#82]
- [x] account system UI/UX design implementation

**Comment by iamtamaghna** [comment]
![IMG_0063](https://user-images.githubusercontent.com/9979182/75989996-34eda780-5f1a-11ea-978e-5007341e9e11.JPG)

**Comment by iamtamaghna** [comment]
[](url)

**Comment by iamtamaghna** [comment]
![IMG_0109](https://user-images.githubusercontent.com/9979182/76753194-8a417880-67a6-11ea-94b4-48d336227c21.JPG)

**Comment by iamtamaghna** [comment]
![image](https://user-images.githubusercontent.com/9979182/77044716-e80fd380-69e5-11ea-9c66-1ed7c6764d64.jpeg)

**Comment by 0mkara** [comment]
Published [v0.1.5](https://github.com/quantanet/ethcode/releases/tag/v0.1.5)
