### ISSUE TITLE
Account Create Key Pair

### ISSUE THREAD

**Issue by Ayanrocks** [quantanet/ethcode#86]
1. Create key pair with/without password
2. Encrypt into JSON with/without password
3. Save into JSON file in Ethcode extension dir.
```
def createAcc():
    home = str(Path.home())
    acct = Account.create('')
    print("New account created : ", acct.address)
    encrypted = Account.encrypt(acct.key, getpass.getpass())
    brkrth_path = home + '/.brokereth'
    print("Saving in ", brkrth_path)
    Path(brkrth_path).mkdir(parents=True, exist_ok=True)
    fileName = brkrth_path + '/' + acct.address +'.json' 
    with open(fileName, 'w') as f:
        f.write(json.dumps(encrypted))
```

* https://ethereum.stackexchange.com/questions/39384/how-to-generate-private-key-public-key-and-address
* https://ethereum.stackexchange.com/questions/11253/ethereumjs-how-to-get-public-key-from-private-key
* https://www.npmjs.com/package/ethereumjs-wallet

**Comment by 0mkara** [comment]
- [ ] create [`create-keypair`]
- [ ] select
- [ ] delete
- [ ] import

**Comment by 0mkara** [comment]
Feature added on #103
