### ISSUE TITLE
File selector UI fix

### ISSUE THREAD

**Issue by 0mkara** [quantanet/ethcode#95]
- [x] file selector should be moved above contract selector
- [x] selector alignment is not correct

![Screenshot from 2020-03-16 14-53-11](https://user-images.githubusercontent.com/13261372/76741725-0bdcda80-6796-11ea-873d-d9693c985ad2.png)

**Comment by iamtamaghna** [comment]
![image](https://user-images.githubusercontent.com/9979182/77051607-8d7c7480-69f1-11ea-9de3-ba1deb29bbe9.jpeg)

**Comment by 0mkara** [comment]
Merged in #118
