### ISSUE TITLE
Advance Deploy UI/UX

### ISSUE THREAD

**Issue by iamtamaghna** [quantanet/ethcode#96]
![image](https://user-images.githubusercontent.com/9979182/77065286-020dde00-6a07-11ea-8f9f-868001ff81f7.jpeg)

**Comment by iamtamaghna** [comment]
![image](https://user-images.githubusercontent.com/9979182/77065322-118d2700-6a07-11ea-8715-32070622e4a6.jpeg)

**Comment by 0mkara** [comment]
Implemented in #118
